language: cpp
before_install:
  - pip install --user cpp-coveralls
script: 
  - cmake --enable-gcov . 
  - make 
  - make test

after_success:
  - coveralls  --root . -E ".*CMakeFiles.*" --gcov-options '\-lp'
